### ISSUE TITLE
加一个

### ISSUE THREAD

**Issue by ldqk** [Hootrix/Chengdu-IT-company-blacklist#30]
中国农业银行，天府三街，离职难，提离职就一直拖延和洗脑，道德绑架，职场PUA；请假难，年假事假都不能请，领导经常洗脑。

**Comment by ldqk** [comment]
还经常逼迫加班，无加班工资。

**Comment by zhaoxude** [comment]
> 中国农业银行，天府三街，离职难，提离职就一直拖延和洗脑，道德绑架，职场PUA；请假难，年假事假都不能请，领导经常洗脑。

提交Pull request

**Comment by ldqk** [comment]
好的
