### ISSUE TITLE
成都沙漏科技有限公司

### ISSUE THREAD

**Issue by danbai225** [Hootrix/Chengdu-IT-company-blacklist#48]
# 公司裁员有我一份

10月19入职，12月7日下午3点被项目管理叫到办公室，被一同叫去的还有同事A、B我们三人。在此之前还有一些人也被叫去过。过去后领导给我们讲述当前游戏行业的不景气，公司经过决定后需要裁员，大概是一半的人30人左右，总共是80左右。我们三个就在其中。他们讲述着他们的不容易，但没有考虑过我和我的同事们，他们也是刚入职的都是试用期，我和A是两个月B是最近的没满一个月，两周左右。并且直到前两天公司还在招人，裁员只是一时之快，没有长远考虑。就在前一天老板在群里发了这个，我竟然没有发觉。

![image.png](https://pwl.stackoverflow.wiki/2021/12/image-d301a12c.png)

查阅了相关法律法规之后我觉得公司已经违反了第四十一条，他们并没有事先通知且告知我们第二天就不用来了。

![image.png](https://pwl.stackoverflow.wiki/2021/12/image-9b439f62.png)

和项目组领导的对话：(试用期不过，就是不过)

录音1:https://danbai-cloud.oss-cn-chengdu.aliyuncs.com/uploads%2F2021%2F12%2F07%2FWF2QJsjn_%E6%B5%B7%E6%98%8C%E5%8D%97%E8%B7%AF87%E5%8F%B7.m4a?Expires=1638883510

4点钟我们去1楼，询问人事是否有补贴，但她说她也是按流程走，让我去问我项目领导。在此我们遇到了同事C他也在名单中，他也是试用期才来十几天。后我询问领导，领导就改口说我们不是裁员，是因试用期不合格被开除，让我们签离职申请走人。我们几个对公司的做法非常不认同，我觉得我应该受到法律的保护，得到我们应有的权益。于是我们僵持走法律途径约定第二天去劳动局仲裁，等待下班打卡。

> 在等待期间我也看到一个美术的妹子被逼着签署离职申请，她嘴里的辩解在领导看来就是废话。“不过就是不过，过不过我说了算。”

以下是同事C和他领导的聊天：

<div align="center">
<img src="https://pwl.stackoverflow.wiki/2021/12/image-53ab8640.png" width="240" >
<img src="https://pwl.stackoverflow.wiki/2021/12/image-19280d4f.png" width="240" >
<img src="https://pwl.stackoverflow.wiki/2021/12/image-d268ecf9.png" width="240" >
<img src="https://pwl.stackoverflow.wiki/2021/12/image-a162fabe.png" width="240" >
 </div>

在18.30左右老板（股东）气凶凶得来了， 并说出我们是不可能拿到赔偿的，并且不签合同这些时日的工资也没有。他先是杀鸡儆猴对着我们吼到谁是xxx（我的姓名）然后当着我面说：“着不签是吧，然后便撕毁合同。”后又对着同事们开始一个一个倒计数 10 9 8 7....1然后同事们顶不住了当时C不在场（他回三街分公司打卡了）。在老板的恐吓下同事们签了合同，解除了劳动关系。而我就回家去了，等我到家突然发现忘记打卡，又返回公司打卡，发现已经被踢出了叮叮团队。不让我打卡，明天我会和C一起去到劳动局。

以下是当时的录音：（我啥都没有）

录音2：https://pwl.stackoverflow.wiki/2021/12/标准录音2-be069b33.mp3

公司名：成都沙漏科技有限公司（成都海棠世家科技有限公司）

![image.png](https://pwl.stackoverflow.wiki/2021/12/image-00aeeaef.png)

我估计公司应该不是第一次这样操作了，我听过他们说前面就裁掉过一整个项目组。老员工也很少就几个领导，面试我的人都不见了。（我是面完之后两个月进的公司）希望大家别遇到这种公司，就嫖你试用期。

**Comment by danbai225** [comment]
我今天和同事一起去了申请了劳动仲裁

**Comment by adlered** [comment]
顶一下

**Comment by Hootrix** [comment]
顶一下

**Comment by xuwuruoshui** [comment]
结局呢

**Comment by kaindy7633** [comment]
还有一点要注意，公司单方解除劳动合同，这段时间你们最好每天上班时间去公司，虽然不能打卡，但你们可以拍视频留证，仲裁的时候可以申请这段时间的工资和赔偿

**Comment by dlfld** [comment]
蹲一个后续

**Comment by xuwuruoshui** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
