### ISSUE TITLE
我也要提交一个公司

### ISSUE THREAD

**Issue by flfps** [Hootrix/Chengdu-IT-company-blacklist#6]
成都森央互动娱乐有限公司
拖欠员工工资，

**Comment by linyuan9999** [comment]
北京众鸣在线科技有限公司  成都技术中心       恶意拖欠工资，，2018年8月份的工资到现在没有发放。

**Comment by Hootrix** [comment]
@flfps   @linyuan9999 
可以直接`pull request`提交呀

**Comment by yugu88** [comment]
成都景和千城，名声臭成了人尽皆知的网红公司，就是因为被乐视辞退的张世明当了技术部领导，啥也不懂，把公司带向了永无止境消耗的路线，没啥产出，最终黄了……
