### ISSUE TITLE
四川省寰宇众恒科技有限公司

### ISSUE THREAD

**Issue by li-jiangming** [Hootrix/Chengdu-IT-company-blacklist#79]
公司项目均处于烂尾状态，经常连夜加班造假数据应付领导检查；与公司签订的劳动合同约定10小时工作制（不要奢求有加班工资，也不会让你调休）；各种恶心你，在职6个月只有1个月准时发工资，而且每次发工资都是凌晨十二点左右；经常强制无效加班到凌晨，不加班就会让你走人；公司绩效占工资的一半，要赶你走的时候通常都会恶意绩效考核（比如扣除60%的绩效），以此方式逼你主动离职；最后注意公司的部门领导和人事找你谈话会给你下套并录音，需特别注意公司领导层请完全零信任相处，不要存在任何幻想，他们给不了什么好处，能给你的就是恶意绩效考核和让你走人。

**Comment by detonateyin** [comment]
已收到您的邮件，谢谢

**Comment by detonateyin** [comment]
已收到您的邮件，谢谢
